version: 2.1
description: |
  An orb for working with Amazon Elastic Container Service (ECS).
  Supports the EC2 and Fargate launch types and Blue/Green deployment
  via CodeDeploy.


jobs:
  build:
    docker:
      - image: trendava/node:latest
    steps:
      - checkout
      - run: npm install
      - run: CI=true 
  test:
    docker:
      - image: trendava/node:latest
    steps:
      - checkout
      - run: npm install
      - run: CI=true 
  client-test:
    docker:
      - image: trendava/node:latest
    steps:
      - checkout
      - run: echo "Tests client side"
      - run: CI=true 
  server-test:
    docker:
      - image: trendava/node:latest
    steps:
      - checkout
      - run: echo "Tests on server-side"
      - run: CI=true 
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - server-test
      - client-test
      - test:
          requires:
            - server-test